### PR TITLE
fix: add missed reserved characters to be encoded

### PR DESCRIPTION
**Pull request by astsiapanay**

### CODE REVIEW

**Review by Maxim-Gadalov — DISMISSED** [review]

**Comment by Maxim-Gadalov** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-341.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by Maxim-Gadalov** [comment]
N2N test are not passed, we need to figure out why

**Comment by astsiapanay** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-341.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by astsiapanay** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-341.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by astsiapanay** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-341.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by astsiapanay** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-341.nightly-test.deltixhub.io
>E2E tests status:

**Comment by astsiapanay** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-341.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by Maxim-Gadalov — APPROVED** [review]

**Pull request merged**
