### PR TITLE
fix: fix big file upload to s3

### LINKED ISSUE #400: Fix big file upload to s3
Error:
```
Multipart upload aborted
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "org.jclouds.io.MutableContentMetadata.getContentLength()" is null
 at org.jclouds.s3.blobstore.S3BlobStore.uploadMultipartPart(S3BlobStore.java:390)
 at com.epam.aidial.core.storage.BlobStorage.storeMultipartPart(BlobStorage.java:100)
 at com.epam.aidial.core.storage.BlobWriteStream.lambda$drainHandler$1(BlobWriteStream.java:171)
 at io.vertx.core.impl.ContextBase.lambda$executeBlocking$0(ContextBase.java:167)
 at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
 at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
 at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(Thread.java:840)
```

### PR DESCRIPTION
**Pull request by Oleksii-Klimov**

### CODE REVIEW

**Comment by Oleksii-Klimov** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-401.nightly-test.deltixhub.io
>E2E tests status: success

**Review by artsiomkorzun — APPROVED** [review]

**Comment by Oleksii-Klimov** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/497727)

**Comment by Oleksii-Klimov** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/497741)

**Comment by dspashynskyi** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-401.nightly-test.deltixhub.io
>E2E tests status: success

**Pull request merged**
