### PR TITLE
fix: Disabled redis cache

### PR DESCRIPTION
**Pull request by vladisavvv**

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
Hey there and thank you for opening this pull request! 👋🏼

We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

Details:

```
Unknown release type "draft" found in pull request title "draft: Disabled redis cache". 

Available types:
 - fix
 - hotfix
 - feat
 - feature
 - chore
```

**Comment by vladisavvv** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/541647)

**Comment by vladisavvv** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-591.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by vladisavvv** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/541658)

**Comment by vladisavvv** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-591.nightly-test.deltixhub.io
>E2E tests status: success

**Pull request closed without merging**
