### PR TITLE
fix: performance API key store degradation

### PR DESCRIPTION
**Pull request by astsiapanay**

### CODE REVIEW

**Comment by astsiapanay** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-325.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by astsiapanay** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-325.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by astsiapanay** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-325.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by astsiapanay** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-core-pr-325.nightly-test.deltixhub.io
>E2E tests status: success

**Review by Maxim-Gadalov — APPROVED** [review]

**Pull request merged**
